config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  get 'games' => 'games#index'
  get 'games/flash_cards' => 'flash_cards#index'
  get 'games/flash_cards/:id' => 'flash_cards#show'
  post 'games/flash_cards/:id/edit' => 'flash_cards#edit'
  # get 'games/:game' => 'games#show'
  get "/statics/:static" => 'statics#show'

  resources :words

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "welcome#index"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/game.rb
class Game < ApplicationRecord
end

app/models/word.rb
class Word < ApplicationRecord
  validates :definition, presence: true, length: {
    minimum: 2,
    message: "Definition cannot be empty"
  }
  validates :part_of_speech, inclusion: {
    in: %w(verb noun adjective),
    message: "%{value} must be verb, noun or adjective"
  }
  validates :score, numericality: {only_integer: true,
    greater_than_or_equal_to: 0,
    less_than_or_equal_to: 100
  }
  def definition_list
    return definition.split(";")
  end
  # Retrieve words that are in the definition of this word
  # and in the list of words....ugh
  # def related_words
  #   rwords = Word.
  # end
  def increment_score
    self.score += 1 if self.score < 100
  end
  def decrement_score
    self.score -= 1 if self.score > 0
  end
  # get a random word from the highest scores
  def self.retrieve(l=1)
    i = 5
    w2 = Word.maximum(:score)
    w1 = w2-i
    r = Word.where(score: w1..w2).limit(l).order("RANDOM()")
    while r.length < l
      w1 = w2-i # increase range
      r = Word.where(score: w1..w2).limit(l).order("RANDOM()")
      i += 1
    end
    return r
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/flash_cards_controller.rb
class FlashCardsController < ApplicationController
  def index
    @word = Word.retrieve()[0]
  end
  def show
    @word = Word.find(params[:id])
    respond_to do |format|
      format.js
    end
  end
  def edit
    @word = Word.find(params[:id])
    # logger.debug(params)
    if params[:score_action] == "increment"
      @word.increment_score
      @word.save
    elsif params[:score_action] == "decrement"
      @word.decrement_score
      @word.save
    end
    redirect_to "/games/flash_cards"
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  def index
  end
end

app/controllers/statics_controller.rb
class StaticsController < ApplicationController
  def show
    render template: "statics/#{params[:static]}"
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    # I can change the output of what index to show based
    # on who is logged in
  end
end

app/controllers/words_controller.rb
class WordsController < ApplicationController
  def new
    @word = Word.new
  end
  def edit
    @word = Word.find(params[:id])
  end
  def update
    @word = Word.find(params[:id])
    if @word.update(word_params)
      redirect_to @word
    else
      render 'edit'
    end
  end
  def create
    # render plain: params[:word].inspect
    @word = Word.new(word_params)
    if @word.save
      redirect_to @word
    else
      render 'new'
    end
  end
  def show
    @word = Word.find(params[:id])
    @definitions = @word.definition_list
  end
  def index
    @words = Word.all.page(params[:page] || 1)
  end
  def destroy
    @word = Word.find(params[:id])
    @word.destroy
    redirect_to words_path
  end

  private
  def word_params
    h = params.require(:word).permit(:word, :part_of_speech, :definition)
    h[:editable] = true
    return h
  end
  # def definition_list
  #   return [] if not @word
  #   return @word.definition.split(';')
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flash_cards_helper.rb
module FlashCardsHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/words_helper.rb
module WordsHelper
end

app/views/flash_cards/index.html.erb
<h1>Flash Cards</h1>
<p>Flip the 'card' to see the definition.</p>
<p><%= link_to 'Next Card', "/games/flash_cards" %></p>

<div class="box red">
  <p><strong>Word:</strong> <%= @word.word %></p>
  <p><strong>Part of Speech:</strong> <%= @word.part_of_speech %></p>
  <p><%= link_to 'Flip', "/games/flash_cards/#{@word.id}", remote: true, id: 'flip' %></p>
</div>
<div id="hidden-div" class="box red hidden">
  <ul id="flash_answer"></ul>
  <div class="flex-box">
    <%= form_tag "/games/flash_cards/#{@word.id}/edit" do %>
      <%= hidden_field_tag "score_action", "decrement" %>
      <%= image_submit_tag "dialog-ok-apply.png" %>
    <% end %>
    <%= form_tag "/games/flash_cards/#{@word.id}/edit" do %>
      <%= hidden_field_tag "score_action", "increment" %>
      <%= image_submit_tag "edit-delete.png" %>
    <% end %>
  </div>
</div>
<p><%= link_to 'Back', controller: 'games' %></p>

app/views/flash_cards/show.js.erb
// log("<%= @word.definition_list %>");
var l = $('#flash_answer');
<% @word.definition_list.each do |d| %>
  l.insert("li","<%= d %>");
<% end %>
var d = $('#hidden-div');
d.classList.remove("hidden");

app/views/games/index.html.erb
<h1>Vocabulary Games</h1>
<p>Games to help you learn.</p>
<p><%= link_to 'Back', welcome_index_path %></p>
<p><%= link_to 'Flash Cards', '/games/flash_cards' %></p>
<p>multiple choice</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GRE Practice</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/statics/numbers.html.erb
<h1>Number Properties</h1>
<p><%= link_to 'Back', root_path %></p>
<div class="box">
  <p>Negative numbers are even or odd.</p>
  <p>0 is even.</p>
  <p>0 and 1 are not prime.</p>
  <p>2 is the only even prime.</p>
</div>

<div class="box">
  <p>Rules for evens and odds.</p>
  <ul>
    <li>even + even = odd</li>
    <li>even + odd = odd</li>
    <li>odd + odd = even</li>
    <li>even * even = even</li>
    <li>even * odd = even</li>
    <li>odd * odd = odd</li>
  </ul>
</div>
<div class="box">
  <h2>Tips</h2>
  <p>Plug in each of the following for comparative questions to eliminate "Cannot be determined by the information given."</p>
  <ul>
    <li>Fraction</li>
    <li>Repeats</li>
    <li>1</li>
    <li>0</li>
    <li>Extreme</li>
    <li>Negative</li>
  </ul>
  <p>Plug in numbers by observing the following.</p>
  <ul>
    <li>Avoid 1 and 0.</li>
    <li>Don't use numbers that are in the problem.</li>
    <li>Use different numbers for different unknowns.</li>
    <li>Don't use conversion numbers. (ie. 60)</li>
  </ul>
  <p>Use the common denominator as a test number when dealing with fraction problems.</p>
  <p>Remember to flip an inequality sign if multiply or divide by a negative. (When the sign changes.)</p>
</div>

<div class="box purple">
  <h2>Factors and Multiples</h2>
  <p><span class="label">Factor:</span>A number that will divide another evenly.</p>
  <p><span class="label">Multiple:</span>Results of multiplying an integer.</p>
  <h2>Rules of Division</h2>
  <p>To determine if an integer is divisible by ... do ...</p>
  <ol start="2">
    <li>Unit digit is divisible by 2.</li>
    <li>The sum of its digits is divisible by 3.</li>
    <li>Last two digits form a number that is divisible by 4.</li>
    <li>Units digit is divisible by 0 or 5.</li>
    <li>Divisible by both 2 and 3.</li>
    <li>Nothing can help you.</li>
    <li>Last three digits form a number that is divisible by 8.</li>
    <li>The sum of its digits is divisible by 9.</li>
    <li>Units digit is 0.</li>
  </ol>
</div>

<div class="box blue">
  <h2>Common Fractions</h2>
  <table>
    <tr><td>0.01</td><td>1/100</td></tr>
    <tr><td>0.1</td><td>1/10</td></tr>
    <tr><td>0.2</td><td>1/5</td></tr>
    <tr><td>0.25</td><td>1/4</td></tr>
    <tr><td>0.333...</td><td>1/3</td></tr>
    <tr><td>0.4</td><td>2/5</td></tr>
    <tr><td>0.5</td><td>1/2</td></tr>
    <tr><td>0.6</td><td>3/5</td></tr>
    <tr><td>0.666...</td><td>2/3</td></tr>
    <tr><td>0.75</td><td>3/4</td></tr>
    <tr><td>0.8</td><td>4/5</td></tr>
  </table>
</div>

<div class="box">
  <h2>Formulas</h2>
  <p>
    <span class="math">Percentage Change =</span>
    <span class="math fraction">
      <span class="numerator">Difference</span>
      <span class="denominator">Original</span>
    </span>
    <span class="math"> * 100</span>
  </p>
</div>

app/views/welcome/index.html.erb
<h1>GRE Practice</h1>
<h2>General Information</h2>
<p><%= link_to 'Number Properties', '/statics/numbers' %></p>
<h2>Vocabulary</h2>
<p><%= link_to 'Dictionary', controller: 'words' %></p>
<p><%= link_to 'Word Games', controller: 'games' %></p>

app/views/words/_form.html.erb
<%= form_with model: @word, local: true, class: "box" do |form| %>
  <% if @word.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@word.errors.count, "Error") %> prohibited this word from being saved.
      </h2>
      <ul>
        <% @word.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= form.label :word %><br>
    <%= form.text_field :word, disabled: @word.editable? %>
  </p>
  <p>
    <%= form.label :part_of_speech %><br>
    <%= form.select :part_of_speech, options_for_select(
        [['verb','verb'],['noun','noun'],['adjective','adjective']]
      ), disabled: @word.editable? %>
  </p>
  <p>
    <%= form.label  :score %><br>
    <%= form.number_field :score, in: 0..100, step: 1 %>
  <p>
    <%= form.label :definition %><br>
    <%= form.text_area :definition, disabled: @word.editable?%>
  </p>
  <p>
    <%= form.label :sentence %><br>
    <%= form.text_area :sentence %>
  </p>

  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/words/_word.html.erb
<tr>
  <td><%= word.word %></td>
  <td><%= word.part_of_speech%></td>
  <td><%= link_to 'Show', word_path(word) %> |</td>
  <td><%= link_to 'Edit', edit_word_path(word) %> |</td>
  <td><%= link_to_if word.editable?, 'Delete', word_path(word), method: :delete,
            data: {confirm: "Permanently delete word?"} %></td>
</tr>

app/views/words/edit.html.erb
<h1>Edit Word</h1>
<p><%= link_to 'Back', words_path %></p>
<%= render 'form' %>

app/views/words/index.html.erb
<h1>Dictionary</h1>
<%= link_to 'New Word', new_word_path %> |
<%= link_to 'Back', welcome_index_path %>
<table>
  <thead><tr>
    <th>Word</th>
    <th>Part of speech</th>
  </tr></thead>
  <tbody id="words">
    <%= render @words %>
  </tbody>
</table>
<div id = "paginator"><%= paginate @words, remote: true %></div>

app/views/words/index.js.erb
var u = $("#words");
u.innerHTML = "<%= j(render @words) %>";
var p = $("#paginator");
p.innerHTML = "<%= j(paginate(@words, remote: true).to_s) %>";

app/views/words/new.html.erb
<h1>Add a Word</h1>
<p>Add a new word to the dictionary. It will be rejected if the word already exists.</p>
<p><%= link_to 'Back', words_path %></p>
<%= render 'form' %>

app/views/words/show.html.erb
<p>
  <strong>Word:</strong>
  <%= @word.word %>
</p>
<p>
  <strong>Part of speech:</strong>
  <%= @word.part_of_speech %>
</p>
<p>
  <strong>Definitions</strong>
  <ul>
    <% @definitions.each do |d| %>
      <li><%= d %></li>
    <% end %>
  </ul>
</p>

<%= link_to 'Edit', edit_word_path(@word) %> | <%= link_to 'Back', words_path %>